### PR TITLE
Formats the source code

### PR DESCRIPTION
**Pull request by illusionalsagacity**
I noticed that several files were being re-formatted, IMO it'd be good to run this before some larger PRs start including these formatting changes.

### CODE REVIEW

**Comment by illusionalsagacity** [comment]
🙃 will have to revisit this and up the CI versions. `graphql-ppx` has a `dev` tag that allows rescript 10, but not sure if we ought to do that or just use legacy peer deps

**Comment by jeddeloh** [comment]
Makes sense. Maybe we should create a `feature--rescript-11` branch that you can point future PRs at until it's ready to go into `main`?

**Comment by illusionalsagacity** [comment]
> Makes sense. Maybe we should create a `feature--rescript-11` branch that you can point future PRs at until it's ready to go into `main`?

Yeah makes sense to me

**Comment by jeddeloh** [comment]
FYI, I created that branch if you want to point PRs to it.

**Comment by illusionalsagacity** [comment]
@jeddeloh I changed the target back, assuming that's what you meant by your comment

**Comment by jeddeloh** [comment]
I was actually just wondering if we wanted to merge this into the feature branch, but looks like we're confident in our approach now. Merging into main is fine

**Review by jeddeloh — APPROVED** [review]

**Pull request merged**
