### PR TITLE
feat: change extended react hook names

### LINKED ISSUE #39: Change React Hook names
Right now for both queries and mutation, there is `use` function generated. I'm wondering if it would be possible to change it to `useQuery` for queries and `useMutation` for mutations. It would make it more readable if this module is a query or mutation.

### PR DESCRIPTION
**Pull request by baransu**
Please let me know if you're ok with this change.
***
Closes #39

### CODE REVIEW

**Comment by baransu** [comment]
PS. Amazing work with this library 🎉

**Comment by jfrolich** [comment]
From the definition it should be pretty clear what is a query and what is a mutation / subscription right? I think this will mostly add extra characters to type.

**Comment by jeddeloh** [comment]
> Please let me know if you're ok with this change.
Commented in the issue. I think deserves further discussion.

> P.S. Amazing work with this library 🎉
I'm only riding on the coattails of the amazing `graphql-ppx`. Thanks for all you've done there!

**Comment by jeddeloh** [comment]
Closing since master has diverged quite a way since.

**Pull request closed without merging**
